# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "280bf17d291913ebe573666c5b5439d5"
application_url = "http://localhost:5174"
embedded = true
name = "matr-front"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,read_draft_orders"

[auth]
redirect_urls = [ "http://localhost:5174/api/shopify/callback" ]

[webhooks]
api_version = "2026-10"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
